# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kimita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
    ]
