# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimita', '0002_auto_20190511_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='kimita.languages'),
        ),
    ]
