# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-11 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kimita', '0003_auto_20190511_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(to='kimita.languages'),
        ),
    ]
